---
inputs:	
- type: git	
  branch: master	
  service: ${GIT_REPO}	
  path: .tekton
triggers:
- type: git
  name: Git PR Trigger
  url: https://github.com/SidneyJiang/tekton-example.git
  branch: master
  events: {"push":true,"pull_request":true,"pull_request_closed":false}
  eventListener: listener
- type: git
  name: Git PR Trigger 2
  service: ${GIT_REPO_TRIGGER}
  branch: integration
  events: {"push":true,"pull_request":true,"pull_request_closed":true}
  eventListener: listener
- type: manual
  name: Manual Trigger
  eventListener: listener
- type: timer
  name: Timmer Trigger
  eventListener: listener
- type: generic
  name: Generic Trigger
  eventListener: listener
  secret: 
    value: top secret
    type: tokenMatches
    source: payload
    keyName: taken
properties:
- name: apikey
  value: ${API_KEY}
  type: SECURE
- name: cluster
  value: ${PROD_CLUSTER_NAME}
  type: text 
- name: registryNamespace
  value: ${REGISTRY_NAMESPACE}
  type: text 
- name: clusterNamespace
  value: ${PROD_CLUSTER_NAMESPACE}
  type: text
- name: clusterRegion
  value: ${PROD_REGION_ID}
  type: text
- name: registryRegion
  value: ${REGISTRY_REGION_ID}
  type: text
- name: repository
  value: ${REPOSITORY}
  type: text
- name: revision
  value: ${REVISION}
  type: text
private_worker: ${PRIVATE_WORKER}
