version: '2'
messages:
  $i18n: locales.yml
template:
  name:
    $ref: "#/messages/template.name"
  description:
    $ref: "#/messages/template.description"
  header: '![](toolchain.svg?localize)'
  icon: secure-lock-kubernetes.svg
  required:
    - build
    - repo
    - repo-trigger
  info:
    git url: >
      "[" + $env.repository + "]" +
        "(" + $env.repository + ")"
    git branch: >
      "[" + $env.branch + "]" +
        "(" + $env.repository +
          "/tree/" + $env.branch + ")"
toolchain:
  name: 'simple-tekton-toolchain-{{timestamp}}'
  template:
    getting_started:
      $ref: "#/messages/template.gettingStarted" 
services:
  privateWorker:
    service_id: private_worker
    parameters:
      name: private-worker
  triggerPrivateWorker:
    service_id: private_worker
    parameters:
      name: trigger-private-worker
  repo:
    service_id: githubconsolidated
    parameters:
      repo_name: '{{toolchain.name}}'
      source_repo_url: 'https://github.com/open-toolchain/hello-tekton'
      type: clone
      has_issues: true
      enable_traceability: true
  repo-trigger:
    service_id: githubconsolidated
    parameters:
      repo_name: '{{toolchain.name}}-trigger'
      repo_url: 'https://github.com/SidneyJiang/tekton-example'
      type: link
      has_issues: false
      enable_traceability: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      type: tekton
      ui-pipeline: true
      configuration:
        content:
          $text: tekton.yaml
        env:
          GIT_REPO: repo
          GIT_REPO_TRIGGER: repo-trigger
          CF_APP_NAME: '{{form.pipeline.parameters.app-name}}'
          REGISTRY_REGION_ID: '{{form.pipeline.parameters.registry-region}}'
          REGISTRY_NAMESPACE: '{{form.pipeline.parameters.registry-namespace}}'
          API_KEY: '{{form.pipeline.parameters.api-key}}'
          PROD_REGION_ID: '{{form.pipeline.parameters.prod-region}}'
          PROD_CLUSTER_NAME: '{{form.pipeline.parameters.prod-cluster-name}}'
          PROD_CLUSTER_NAMESPACE: '{{form.pipeline.parameters.prod-cluster-namespace}}'
          REPOSITORY: '{{services.repo.parameters.source_repo_url}}'
          REVISION: master
          PRIVATE_WORKER: '{{services.privateWorker.parameters.name}}'
          TRIGGER_PRIVATE_WORKER: '{{services.triggerPrivateWorker.parameters.name}}'
        execute: Manual Trigger
  webide:
    service_id: orion
form:
  pipeline:
    parameters:
      app-name: '{{services.repo.parameters.repo_name}}'
      prod-cluster-namespace: prod
    schema:
      $ref: deploy.json
